on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      sha:
        required: false
        default: ${{ github.sha }}
        type: string
    secrets:
      DEPLOY_DIR:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:

      #restore latest cache
      - uses: actions/cache/restore@v4
        with:
          path: build
          key: vite-assets-unknown
          restore-keys: vite-assets-

      # Courtesy of https://blog.benoitblanchon.fr/github-action-run-ssh-commands/
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host deploy
            HostName $SSH_HOST
            Port $SSH_PORT
            User $SSH_USER
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}

      - name: Run deploy script by ssh
        run: ssh deploy 'cd ${{ secrets.DEPLOY_DIR }} && bash ./scripts/deploy.sh ${{inputs.sha}} --no-interaction'

      - name: Updates dist
        run: scp -Ar build/ deploy:${{ secrets.DEPLOY_DIR }}/public/build/
