name: release-please

on:
  push:
    branches: [ main ]

jobs:

  #Base release please workflow
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      sha: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
          #default-branch: main

  deploy-release-to-staging:
    needs: release-please
    uses: ./.github/workflows/deploy.yml
    if: ${{ needs.release-please.outputs.release_created }}
    secrets: inherit
    with:
      environment: staging
      sha: ${{ needs.release-please.outputs.sha }}

  #There is a 15 minutes timeout for prod real deploy
  deploy-release-to-production:
    needs: [release-please,deploy-release-to-staging]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: production
      sha: ${{ needs.release-please.outputs.sha }}

