name: release-please

on:
  push:
    branches: [ main ]

jobs:
  release-please:
    runs-on: ubuntu-latest
    uses: google-github-actions/release-please-action@v3
    with:
      release-type: simple
      #default-branch: main

  deploy-release-to-staging-and-snapshot:
    runs-on: ubuntu-latest
    environment: staging

    if: ${{ steps.release.outputs.release_created }}

    steps:
        - uses: actions/checkout@v3
          with:
            ref:${{ steps.release.outputs.sha }}

        - uses: ./.github/workflows/deploy.yml
            with:
              sha: ${{ steps.release.outputs.sha }}
            secrets:inherit

        #Update version to snapshot
        - name: set next version to snapshot
          run: |
            git config --global user.name github-action
            git config --global user.email github-action@noreply.com
            git co main
            echo "snapshot" > version.txt
            git stage version.txt
            git commit -m "chore(release): set back version to snapshot"
            git push

  deploy-release-to-production:
    runs-on: ubuntu-latest
    environment: production

    if: ${{ steps.release.outputs.release_created }}
    uses: ${{ github.repository }}/.github/workflows/deploy.yml@${{ steps.release.outputs.sha }}
    secrets: inherit
    with:
      sha: ${{ steps.release.outputs.sha }}

