name: release-please

on:
  push:
    branches: [ main ]

jobs:

  #Base release please workflow
  release-please:
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          #default-branch: main

  deploy-release-to-staging:
    if: ${{ steps.release.outputs.release_created }}

    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: staging
      sha: ${{ steps.release.outputs.sha }}

  #There is a 15 minutes timeout for prod real deploy
  deploy-release-to-production:

    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: production
      sha: ${{ steps.release.outputs.sha }}

  set-snapshot-version-after-release:
    if: ${{ steps.release.outputs.release_created }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref:${{ steps.release.outputs.sha }}

      #Update version to snapshot
      - name: set next version to snapshot
        run: |
          git config --global user.name github-action
          git config --global user.email github-action@noreply.com
          git co main
          echo "snapshot" > version.txt
          git stage version.txt
          git commit -m "chore(release): set back version to snapshot"
          git push
