name: release-please

on:
  push:
    branches: [ prod ]

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: pm2etml-intranet
